# Generated by Django 5.2.6 on 2025-09-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="session_url",
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PAID", "Paid"),
                    ("CANCELED", "Canceled"),
                    ("EXPIRED", "Expired"),
                ],
                default="PENDING",
                max_length=15,
            ),
        ),
    ]
