# Generated by Django 5.2.6 on 2025-09-20 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="cover",
            field=models.CharField(
                choices=[("HARD", "Hard"), ("SOFT", "Soft")],
                default="HARD",
                max_length=20,
            ),
        ),
    ]
